= Getting Started 


== Creating a Quarkus App

It is recommended to generate a starter app using the https://code.quarkus.io/?e=io.quarkiverse.couchbase%3Aquarkus-couchbase[Quarkus Code Starter].
If you already have a Quarkus app on hand, install with Maven or Gradle as follows:


[{tabs}] 
==== 
Maven::
+
--
Add this to your `pom.xml`:


[source,xml]
----
<dependency>
  <groupId>io.quarkiverse.couchbase</groupId>
  <artifactId>quarkus-couchbase</artifactId>
  <version>1.0.0</version>
</dependency>
----
--


Gradle::
+
--
[source,groovy,subs="+attributes"]
----
dependencies {
    implementation 'io.quarkiverse.couchbase:quarkus-couchbase:1.0.0'
}
----
--
====




== Configuring Couchbase

Configure the connection in your `application.properties` file, typically located in `src/main/resources`:

[source,properties]
----
quarkus.couchbase.connection-string=localhost
quarkus.couchbase.username=username
quarkus.couchbase.password=password
----

For additional configuration options, refer to the https://docs.quarkiverse.io/quarkus-couchbase/dev/configuration.html[Quarkus Configuration Guide] or https://javadoc.io/doc/io.quarkiverse.couchbase/quarkus-couchbase/latest/index.html[API Reference].


== Using the Extension

The extension produces an Application-scoped `Cluster` bean that can be injected using the jakarta annotation `@Inject`:

[source,java]
----
public class QuarkusExample {
    @Inject
    Cluster cluster;
}
----

From there, you can use the Cluster object like you normally would with the Java SDK.
Refer to the https://docs.quarkiverse.io/quarkus-couchbase/dev/index.html[Quarkus Guide] for an example using `quarkus-rest` to create HTTP endpoints.