= Couchbase Quarkus Release Notes
:description: Release notes for the Couchbase Quarkus Java Extension.
:page-toclevels: 2



[abstract]
{description}

== Couchbase Quarkus 1.4 Releases

=== Version 1.4.0 (5 June 2026)

https://javadoc.io/doc/io.quarkiverse.couchbase/quarkus-couchbase/1.4.0/index.html[API Reference]

==== New Features

* Added an injectable `Bucket` bean

==== Improvements

* DevService TestContainer now ignores the connection-string (connection-string must _not_ be set in order to start the Couchbase container, as it's auto-contigured).
* Upgraded to Quarkus 3.36.0




== Couchbase Quarkus 1.3 Releases

=== Version 1.3.0 (27 February 2026)

https://javadoc.io/doc/io.quarkiverse.couchbase/quarkus-couchbase/1.3.0/index.html[API Reference]

==== New Features

* Added support for Dynamic Ports when using TestContainers.

==== Improvements

* Upgraded to Couchbase Java SDK `3.10.1`.



== Couchbase Quarkus 1.2 Releases

=== Version 1.2.0 (24 October 2025)

https://javadoc.io/doc/io.quarkiverse.couchbase/quarkus-couchbase/1.2.0/index.html[API Reference]

==== New Features

* Added support for TLS connections in native-mode, either to Capella using the packaged certificate, or using a path to a custom certificate.

==== Improvements


* Upgraded to Couchbase Java SDK `3.9.2`.
* Added additional security configuration options.


== Couchbase Quarkus 1.1 Releases


=== Version 1.1.0 (14 May 2025)

https://javadoc.io/doc/io.quarkiverse.couchbase/quarkus-couchbase/1.1.0/index.html[API Reference]

==== New Features

* Added a configuration item for `preferredServerGroup` to the `application.properties` file.

==== Improvements

* Upgraded Couchbase Java SDK from 3.7.7 -> 3.8.0
* Upgraded `metrics-micrometer` from 0.7.6 -> 0.8.0
* Upgraded Quarkus from 3.17.5 -> 3.20.0
* Upgraded `@ConfigMapping` to use the new `@ConfigRoot` (removed `AlegacyConfigRoot=true` compiler argument)
* Removed Graal compiler arguments from `native-image.properties` in favor of a `BuildStep`.



== Couchbase Quarkus 1.0 Releases


=== Version 1.0.0 (17 January 2025)

https://javadoc.io/doc/io.quarkiverse.couchbase/quarkus-couchbase/1.0.0/index.html[API Reference]

Initial GA release.

